version: '2.0'

services:
  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    container_name: spark-master
    hostname: spark-master
    ports:
    - "8088:8088"
    - "7077:7077"
    environment:
    - "constraint:node==spark-master"
    volumes:
    - ./../conf/:/conf/
    - ./../data:/raw_data
    - ./:/app
    mem_limit: 1g
  spark-worker-1:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
    - spark-master
    ports:
    - "8081:8081"
    environment:
    - "SPARK_MASTER=spark://spark-master:7077"
    - "constraint:node==spark-master"
    volumes:
    - ./../conf/:/conf/
    mem_limit: 1g
#  spark-worker-2:
#    image: bde2020/spark-worker:2.4.0-hadoop2.7
#    container_name: spark-worker-2
#    hostname: spark-worker-2
#    depends_on:
#    - spark-master
#    ports:
#    - "8082:8082"
#    environment:
#    - "SPARK_MASTER=spark://spark-master:7077"
#    - "constraint:node==spark-worker-1"
#    volumes:
#    - ../conf/:/conf/
#    mem_limit: 1g

